### PR TITLE
Add properties used by the registry to the package's ProviderInfo definition

### PR DESCRIPTION
**Pull request by praneetloke**

### CODE REVIEW

**Review by stack72 — COMMENTED** [review]
Should we add Publisher as well?

**Comment by praneetloke** [comment]
> Should we add Publisher as well?

Ah yes, indeed! Adding it now...

**Comment by praneetloke** [comment]
Done @stack72

**Comment by stack72** [comment]
Thanks @praneetloke  - this is all awesome :)

**Pull request merged**
